version: '3.8'

services:
  vault:
    image: vault:1.15.2
    container_name: vault
    restart: unless-stopped
    ports:
      - "8200:8200"
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: myroot
      VAULT_DEV_LISTEN_ADDRESS: 0.0.0.0:8200
      VAULT_ADDR: http://0.0.0.0:8200
    cap_add:
      - IPC_LOCK
    volumes:
      - vault_data:/vault/data
      - ./scripts:/scripts
    command: >
      sh -c "vault server -dev -dev-listen-address=0.0.0.0:8200 &
             sleep 10 &&
             /scripts/setup-vault.sh &&
             wait"

  postgres:
    image: postgres:15
    container_name: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: vaultapp
      POSTGRES_USER: vaultuser
      POSTGRES_PASSWORD: secretpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build: .
    container_name: vault-app
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: local
      SPRING_CLOUD_VAULT_URI: http://vault:8200
      SPRING_CLOUD_VAULT_TOKEN: myroot
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/vaultapp
    depends_on:
      - vault
      - postgres
    volumes:
      - ./scripts:/scripts

volumes:
  vault_data:
  postgres_data: