spring:
  cloud:
    vault:
      uri: http://localhost:8200
      authentication: TOKEN
      token: myroot
      ssl:
        enabled: false
      kv:
        enabled: true
        backend: secret
        profile-separator: '/'
        default-context: vault-app

  datasource:
    url: jdbc:postgresql://localhost:5433/vaultapp
    username: vaultuser
    password: secretpassword
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

logging:
  level:
    com.example.vaultapp: DEBUG
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG