spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false

  cloud:
    vault:
      enabled: false

database:
  password: test-password

logging:
  level:
    com.example.vaultapp: INFO
    org.springframework.vault: INFO
    org.springframework.cloud.vault: INFO