server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/vaultapp
    username: vaultuser
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus,vault
  endpoint:
    health:
      show-details: always

logging:
  level:
    com.example.vaultapp: DEBUG
    org.springframework.vault: DEBUG
    org.springframework.cloud.vault: DEBUG