apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: vault-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:15
        env:
        - name: POSTGRES_DB
          value: vaultapp
        - name: POSTGRES_USER
          value: vaultuser
        - name: POSTGRES_PASSWORD
          value: temppassword
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-pvc