apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: myroot
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: 0.0.0.0:8200
        - name: VAULT_ADDR
          value: http://0.0.0.0:8200
        ports:
        - containerPort: 8200
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        lifecycle:
          postStart:
            exec:
              command:
              - sh
              - -c
              - |
                # Wait for Vault to be ready
                sleep 5
                until vault status; do
                  echo "Waiting for Vault to be ready..."
                  sleep 2
                done
                
                # Enable KV secrets engine (ignore if already enabled)
                vault secrets enable -path=secret kv-v2 || echo "KV engine already enabled"
                
                # Create database password secret
                vault kv put secret/vault-app database.password=supersecretpassword
                
                echo "Vault setup completed successfully!"
        command:
        - vault
        - server
        - -dev
        - -dev-listen-address=0.0.0.0:8200
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault-app
spec:
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
  type: ClusterIP