apiVersion: apps/v1
kind: Deployment
metadata:
  name: vault
  namespace: vault-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vault
  template:
    metadata:
      labels:
        app: vault
    spec:
      serviceAccountName: vault-app
      containers:
      - name: vault
        image: hashicorp/vault:1.15.2
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: myroot
        - name: VAULT_DEV_LISTEN_ADDRESS
          value: 0.0.0.0:8200
        - name: VAULT_ADDR
          value: http://127.0.0.1:8200
        ports:
        - containerPort: 8200
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        securityContext:
          capabilities:
            add:
            - IPC_LOCK
        readinessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          successThreshold: 1
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /v1/sys/health
            port: 8200
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 3
          failureThreshold: 3
        command:
        - vault
        - server
        - -dev
        - -dev-listen-address=0.0.0.0:8200
      volumes:
      - name: vault-certs
        secret:
          secretName: vault-certs
---
apiVersion: v1
kind: Service
metadata:
  name: vault
  namespace: vault-app
spec:
  selector:
    app: vault
  ports:
  - port: 8200
    targetPort: 8200
  type: ClusterIP