apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-init-script
  namespace: vault-app
data:
  init.sh: |
    #!/bin/sh
    set -e
    
    echo "Waiting for Vault to be ready..."
    export VAULT_ADDR="https://vault:8200"
    export VAULT_TOKEN="myroot"
    export VAULT_SKIP_VERIFY="true"
    
    # Wait for Vault to be ready using vault status
    until vault status >/dev/null 2>&1; do
      echo "Vault not ready, waiting..."
      sleep 5
    done
    
    echo "Vault is ready, configuring..."
    
    # Enable KV secrets engine (ignore if already enabled)
    vault secrets enable -path=secret kv-v2 || echo "KV engine already enabled"
    
    # Create database password secret
    vault kv put secret/vault-app database.password=supersecretpassword
    
    # Enable Kubernetes auth method
    vault auth enable kubernetes || echo "Kubernetes auth already enabled"
    
    # Configure Kubernetes auth method
    vault write auth/kubernetes/config \
        token_reviewer_jwt="$(cat /var/run/secrets/kubernetes.io/serviceaccount/token)" \
        kubernetes_host="https://$KUBERNETES_PORT_443_TCP_ADDR:443" \
        kubernetes_ca_cert=@/var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    
    # Create policy for the application
    vault policy write vault-app-policy - <<EOF
    path "secret/data/vault-app/*" {
      capabilities = ["read"]
    }
    EOF
    
    # Create a role for the application
    vault write auth/kubernetes/role/vault-app-role \
        bound_service_account_names=vault-app \
        bound_service_account_namespaces=vault-app \
        policies=vault-app-policy \
        ttl=24h
    
    echo "Vault setup completed successfully!"
---
apiVersion: batch/v1
kind: Job
metadata:
  name: vault-init
  namespace: vault-app
spec:
  template:
    spec:
      serviceAccountName: vault-app
      restartPolicy: OnFailure
      containers:
      - name: vault-init
        image: hashicorp/vault:1.15.2
        env:
        - name: VAULT_ADDR
          value: http://vault:8200
        - name: VAULT_TOKEN
          value: myroot
        command:
        - /bin/sh
        - /scripts/init.sh
        volumeMounts:
        - name: init-script
          mountPath: /scripts
          readOnly: true
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
      volumes:
      - name: init-script
        configMap:
          name: vault-init-script
          defaultMode: 0755